export const RESET = 'RESET';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const ADD_TO_CHARACTER = 'ADD_TO_CHARACTER';
export const REMOVE_FROM_CHARACTER = 'REMOVE_FROM_CHARACTER';
export const UPDATE_STAT = 'UPDATE_STAT';
export const UPDATE_SAVE = 'UPDATE_SAVE';
export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_INITIATIVE = 'UPDATE_INITIATIVE';
export const UPDATE_HEALTH = 'UPDATE_HEALTH';
export const UPDATE_SPEED = 'UPDATE_SPEED';
export const UPDATE_DEFENSE = 'UPDATE_DEFENSE';
export const UPDATE_ATTACK = 'UPDATE_ATTACK';
export const UPDATE_ATTACK_META = 'UPDATE_ATTACK_META';
export const UPDATE_EFFECT = 'UPDATE_EFFECT';
export const UPDATE_MANEUVER = 'UPDATE_MANEUVER';
export const ADD_ATTACK = 'ADD_ATTACK';
export const REMOVE_ATTACK = 'REMOVE_ATTACK';
export const ADD_SKILL = 'ADD_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const REORDER_CHARACTER_PROPERTY = 'REORDER_CHARACTER_PROPERTY';
export const TOGGLE_CLASS_SKILL_OVERRIDE = 'TOGGLE_CLASS_SKILL_OVERRIDE';

export const ADD_CHARGE = 'ADD_CHARGE';
export const UPDATE_CHARGE = 'UPDATE_CHARGE';
export const REMOVE_CHARGE = 'REMOVE_CHARGE';
export const RESET_CHARGES = 'RESET_CHARGES';

export const RESET_HEALTH = 'RESET_HEALTH';

export const SELECT_CLASS = 'SELECT_CLASS';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const UPDATE_CLASS_LEVEL = 'UPDATE_CLASS_LEVEL';
export const SELECT_RACE = 'SELECT_RACE';
export const UPDATE_RACE = 'UPDATE_RACE';

export const NEW_SHEET_FAIL = 'NEW_SHEET_FAIL';
export const SAVE_SHEET_SUCCESS = 'SAVE_SHEET_SUCCESS';
export const SAVE_SHEET_FAILURE = 'SAVE_SHEET_FAILURE';
export const LOAD_SHEET_SUCCESS = 'LOAD_SHEET_SUCCESS';
export const RESET_SHEET = 'RESET_SHEET';

export const USER_LOG_IN_ATTEMPT = 'USER_LOG_IN_ATTEMPT';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAILURE = 'USER_LOG_IN_FAILURE';
export const USER_LOG_IN_FORM_SHOW = 'USER_LOG_IN_FORM_SHOW';
export const USER_LOG_IN_FORM_HIDE = 'USER_LOG_IN_FORM_HIDE';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_REGISTER = 'USER_REGISTER';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';